WorkOut/Controllers/ActivityTypeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WorkOut.Data.Interfaces;
using WorkOut.Data.Models;

namespace WorkOut.Controllers
{
    public class ActivityTypeController : Controller
    {
        IActivityTypeRepository typeRepository;

        public ActivityTypeController(IActivityTypeRepository repository)
        {
            typeRepository = repository;
        }

        public IActionResult Index()
        {
            return View(typeRepository.ActivityTypes);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(ActivityType type, IFormFile file)
        {
            if (file != null)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(file.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)file.Length);
                }
                type.Icon = imageData;
            }

            typeRepository.Add(type);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            bool succses = typeRepository.DeleteById(id);

            if (!succses) return NotFound();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ActivityType type = typeRepository.GetById(id);

            if (type == null)
            {
                return NotFound();
            }

            

            return View(type);
        }


        [HttpPost]
        public ActionResult Edit(ActivityType type, IFormFile file)
        {
            if (file != null)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(file.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)file.Length);
                }
                type.Icon = imageData;
            }
            else
            {             
                type.Icon = typeRepository.GetByIdNoTracking(type.Id).Icon;
            }

            typeRepository.Update(type);

            return RedirectToAction("Index");
        }
    }
}

WorkOut/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WorkOut.Data.Identity;

namespace WorkOut.Controllers
{
    public class UserController : Controller
    {
        private readonly WUserManager userManager;

        public UserController(WUserManager userManager)
        {
            this.userManager = userManager;
        }
       
        [Route("User/Id{Id}")]
        public IActionResult Index(int Id)
        {
            User user = userManager.FindByIdAsync(Id.ToString()).Result;

            if (User.GetUserId() == Id)
                return RedirectToAction("Index", "Profile");
            return View(user);
        }


        [Route("Users")]
        public IActionResult Find()
        {
            IEnumerable<User> users = userManager.Users.Where(x=>x.Id != User.GetUserId());

            return View(users);
        }
    }
}

WorkOut/Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WorkOut.Data.Identity;
using WorkOut.Data.Interfaces;
using WorkOut.Data.Models;
using WorkOut.Data.ViewModels;

namespace WorkOut.Controllers
{
    [Authorize]
    public class WorkoutController : Controller
    {
        IWorkoutRepository workoutRepository;
        IActivityTypeRepository activityTypeRepository;
        private readonly WUserManager userManager;

        public WorkoutController(IWorkoutRepository repository, IActivityTypeRepository activityTypeRepository, WUserManager userManager)
        {
            workoutRepository = repository;
            this.activityTypeRepository = activityTypeRepository;
            this.userManager = userManager;
        }

        public ActionResult Index()
        {
            return View(workoutRepository.Workouts.Where(x => x.UserId == User.GetUserId()).Include(x => x.ActivityType).Include(x => x.NumberWorkout).Include(x => x.NumberWorkout.Sets).Include(x => x.DistanceWorkout).OrderByDescending(x => x.DateTimeStart));
        }

        public ActionResult DetailsDistance(int id)
        {
            Workout workout = workoutRepository.Workouts.Where(x => x.Id == id && x.UserId == User.GetUserId()).Include(x => x.DistanceWorkout).Include(x => x.ActivityType).FirstOrDefault();

            if (workout == null)
                return NotFound();

            return View("Distance/DetailsDistance", workout);
        }

        public ActionResult DetailsNumber(int id)
        {
            Workout workout = workoutRepository.Workouts.Where(x => x.Id == id && x.UserId == User.GetUserId()).Include(x => x.NumberWorkout).Include(x => x.NumberWorkout.Sets).Include(x => x.ActivityType).FirstOrDefault();

            if (workout == null)
                return NotFound();

            return View("Number/DetailsNumber", workout);
        }


        public ActionResult DetailsTime(int id)
        {
            Workout workout = workoutRepository.Workouts.Where(x => x.Id == id && x.UserId == User.GetUserId()).Include(x => x.ActivityType).FirstOrDefault();

            if (workout == null)
                return NotFound();

            return View("Time/DetailsTime", workout);
        }

        public ActionResult Create()
        {
            var activityTypes = activityTypeRepository.ActivityTypes.Select(x => new ActivityTypeViewModel { Id = x.Id, CountingType = x.CountingType, NewName = x.Name + " " + x.SubtypeName?.ToLower(), Icon = x.Icon });
            return View(activityTypes);
        }

        /*COUNTER*/
        [Route("Create/Counter")]
        [HttpGet]
        public ActionResult CreateNumber()
        {
            var activityTypes = activityTypeRepository.ActivityTypes.Where(x => x.CountingType == "counter").Select(x => new ActivityTypeViewModel { Id = x.Id, Kcal = x.Kcal, Point = x.Point, CountingType = x.CountingType, NewName = x.Name + " " + x.SubtypeName?.ToLower() });
            return View("Number/CreateNumber", new CreateWorkoutViewModel { ActivityTypes = activityTypes });
        }

        [Route("Create/Counter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateNumber(Workout workout, Set[] sets = null)
        {
            try
            {
                /*POINTS*/
                var activity = activityTypeRepository.GetById(workout.ActivityTypeId.Value);
                int point = 0;

                workout.UserId = User.GetUserId();

                /*SUMMARY COUNT SETS*/
                int sum = 0;
                foreach (var s in sets) sum += s.Value;
                point = (int)Math.Round(activity.Point * sum, MidpointRounding.ToEven);
                workout.Point = point;

                int id = workoutRepository.AddNumber(workout, sets);

                //ADD POINT
                await userManager.AddPointAsync(User, point, "workout", activity.Name);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var activityTypes = activityTypeRepository.ActivityTypes.Where(x => x.CountingType == "counter").Select(x => new ActivityTypeViewModel { Id = x.Id, Kcal = x.Kcal, Point = x.Point, CountingType = x.CountingType, NewName = x.Name + " " + x.SubtypeName?.ToLower() });
                return View("Number/CreateNumber", new CreateWorkoutViewModel { ActivityTypes = activityTypes });
            }
        }

        /*DISTANCE*/
        [Route("Create/Distance")]
        [HttpGet]
        public ActionResult CreateDistance()
        {
            var activityTypes = activityTypeRepository.ActivityTypes.Where(x => x.CountingType == "km").Select(x => new ActivityTypeViewModel { Id = x.Id, Kcal = x.Kcal, Point = x.Point, CountingType = x.CountingType, NewName = x.Name + " " + x.SubtypeName?.ToLower() });
            return View("Distance/CreateDistance", new CreateWorkoutViewModel { ActivityTypes = activityTypes });
        }

        [Route("Create/Distance")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateDistance(Workout workout, DistanceWorkout distanceWorkout = null)
        {
            try
            {
                /*POINTS*/
                var activity = activityTypeRepository.GetById(workout.ActivityTypeId.Value);
                int point = 0;

                workout.UserId = User.GetUserId();


                point = (int)Math.Round(activity.Point * distanceWorkout.Distance, MidpointRounding.ToEven);
                workout.Point = point;

                int id = workoutRepository.AddDistance(workout, distanceWorkout);

                //ADD POINT
                await userManager.AddPointAsync(User, point, "workout", activity.Name);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var activityTypes = activityTypeRepository.ActivityTypes.Where(x => x.CountingType == "km").Select(x => new ActivityTypeViewModel { Id = x.Id, Kcal = x.Kcal, Point = x.Point, CountingType = x.CountingType, NewName = x.Name + " " + x.SubtypeName?.ToLower() });
                return View("Distance/CreateDistance", new CreateWorkoutViewModel { ActivityTypes = activityTypes });
            }
        }


        /*DISTANCE*/
        [Route("Create/Time")]
        [HttpGet]
        public ActionResult CreateTime()
        {
            var activityTypes = activityTypeRepository.ActivityTypes.Where(x => x.CountingType == "time").Select(x => new ActivityTypeViewModel { Id = x.Id, Kcal = x.Kcal, Point = x.Point, CountingType = x.CountingType, NewName = x.Name + " " + x.SubtypeName?.ToLower() });
            return View("Time/CreateTime", new CreateWorkoutViewModel { ActivityTypes = activityTypes });
        }

        [Route("Create/Time")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateTime(Workout workout)
        {
            try
            {
                /*POINTS*/
                var activity = activityTypeRepository.GetById(workout.ActivityTypeId.Value);
                int point = 0;

                workout.UserId = User.GetUserId();


                point = (int)Math.Round(activity.Point * (workout.DateTimeFinish - workout.DateTimeStart).TotalMinutes, MidpointRounding.ToEven);
                workout.Point = point;

                int id = workoutRepository.AddTime(workout);

                //ADD POINT
                await userManager.AddPointAsync(User, point, "workout", activity.Name);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var activityTypes = activityTypeRepository.ActivityTypes.Where(x => x.CountingType == "time").Select(x => new ActivityTypeViewModel { Id = x.Id, Kcal = x.Kcal, Point = x.Point, CountingType = x.CountingType, NewName = x.Name + " " + x.SubtypeName?.ToLower() });
                return View("Time/CreateTime", new CreateWorkoutViewModel { ActivityTypes = activityTypes });
            }
        }



        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            Workout workout = workoutRepository.GetById(id);
            if (workout == null) return NotFound();

            return View(id);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            Workout workout = workoutRepository.Workouts.Where(x => x.Id == id && x.UserId == User.GetUserId()).FirstOrDefault();

            if (workout == null)
                return NotFound();

            bool succses = workoutRepository.DeleteById(id);

            if (!succses) return NotFound();

            return RedirectToAction("Index");
        }


        /*EDIT WORKOUT*/
        [Route("Edit/Number")]
        [HttpGet]
        public ActionResult EditNumber(int id)
        {
            Workout workout = workoutRepository.Workouts.Where(x => x.UserId == User.GetUserId() && x.Id == id).Include(x => x.ActivityType).Include(x => x.NumberWorkout).Include(x => x.NumberWorkout.Sets).Include(x => x.DistanceWorkout).FirstOrDefault();

            if (workout == null)
                return NotFound();

            var activityTypes = activityTypeRepository.ActivityTypes.Where(x => x.CountingType == "counter").Select(x => new ActivityTypeViewModel { Id = x.Id, Kcal = x.Kcal, Point = x.Point, CountingType = x.CountingType, NewName = x.Name + " " + x.SubtypeName?.ToLower() });

            return View("Number/EditNumber", new CreateWorkoutViewModel { ActivityTypes = activityTypes, Workout = workout });
        }

        [Route("Edit/Number")]
        [HttpPost]
        [ValidateAntiForgeryToken]

WorkOut/Views/Shared/_Footer.cshtml
<style>
    .page-footer{ 
  position:relative; 
  bottom:0; 
  width:100%; 
  height:60px; 
}
</style>

<footer class="page-footer font-small blue shadow border-top">
    <div class="footer-copyright text-center py-3">
        © 2019 <a class="text-decoration-none" href="@Url.Action("Index", "Home")"> Work<span style="color:red; font-weight: 500;">Out</span> with US!</a>
    </div>
</footer>

WorkOut/Views/Shared/_Header.cshtml
<style>
    .header {
        padding-left: 100px !important;
        padding-right: 100px !important;
    }

    .logo {
        height: 40px;
        padding-right: 20px;
        padding-bottom: 3px;
    }

    .first-text {
        font-weight: 700;
    }

    .second-text {
        color: red;
        font-weight: 500;
    }

    .my-avatar {
        height: 40px;
        width: 40px;
    }
</style>


<div class="header d-flex flex-column flex-md-row align-items-center p-3  bg-white border-bottom box-shadow">

    <h5 class="my-0 mr-md-auto font-weight-normal"><a style="text-decoration: none; color: currentColor;" href="@Url.Action("Index", "Home")"><img class="logo" src="~/Content/icon/header/dumbbell.png"><span class="first-text">Work</span><span class="second-text">Out</span></a></h5>


    @if (User.Identity.IsAuthenticated == false)
    {
        <a class="btn btn-outline-primary mr-3" href="@Url.Action("Login", "Account")">Sign up</a>
        <a class="btn btn-outline-danger" href="@Url.Action("Register", "Account")">Register</a>
    }
    else
    {
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="@Url.Action("Index", "ActivityType")">Activity types</a>
            <a class="p-2 text-dark" href="@Url.Action("Index", "Workout")">Workout</a>
            <a class="p-2 text-dark" href="@Url.Action("Find", "User")">Users</a>
        </nav>
        <a href="@Url.Action("Index", "Profile")" class="mr-4 text-decoration-none ">
            @if (UserManager.GetUserAsync(User).Result.Avatar != null)
            {
                <img class="my-avatar rounded-circle ml-5" src="data:image/jpeg;base64,@(Convert.ToBase64String(UserManager.GetUserAsync(User).Result.Avatar))" />
            }
            else
            {
                <img class="my-avatar rounded-circle ml-5" src="~/Content/icon/header/avatar.png" />
            }
            &nbsp; @User.Identity.Name
        </a>
        <form method="post" asp-controller="Account" asp-action="LogOff">
            <input class="btn btn-outline-danger" type="submit" value="Logout" />
        </form>
    }
</div>

WorkOut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=devive-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/Content/favicon.ico" />
    <style>
        html { 
            height:100%; 

        }
        body {
            display: flex;
            flex-direction: column;
            height: 100%;
            padding:0; margin:0; position:relative; 
        }

        .body-content{
           flex-grow: 5;
        }
    </style>
</head>
<body>

    @await Html.PartialAsync("_Header")

    <div class="container body-content px-0 py-3">
        @RenderBody()
    </div>

    @await Html.PartialAsync("_Footer")
</body>
</html>